### ISSUE TITLE
Sometimes hangs installing wget

### ISSUE THREAD

**Issue by jkwatson** [trautonen/heroku-buildpack-oracle-java#2]
I've been seeing that this buildpack often stalls at the step where it is installing wget.

I see something like this on the console:

```
Counting objects: 32240, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (9934/9934), done.
Writing objects: 100% (32240/32240), 12.73 MiB | 1.21 MiB/s, done.
Total 32240 (delta 12228), reused 32136 (delta 12191)
remote: Compressing source files... done.
remote: Building source:
remote:
remote: -----> Fetching custom git buildpack... done
remote: -----> Java app detected
remote: -----> Installing wget... (downloading...)Verifying deploy...........................................................
```

**Comment by jkwatson** [comment]
never mind...i think this is a general issue with heroku not being responsive.  seems to work fine, even when it goes into this long loop.

**Comment by trautonen** [comment]
The stall is because the buildpack actually downloads and compiles whole wget, which takes a while. I could probably use some precompiled binary to make it faster. Subsequential builds of the same app should be faster though as the binary is stored in the permanent storage of slug builder.

Wget is not installed by default in the Heroku's Cedar stack and I'm not aware of any other tools that can work around the cookie verification that Oracle requires for JDK download.

**Comment by jkwatson** [comment]
Thanks for the info! I wouldn't have guessed that was what was going on.  No luck with curl?
